HOST_IP = "localhost"
USER = "root"
PASSWORD = "sLuPeR###!26%"
GROUP_NAME = "Group4"
DEVICE_ID = "Device4"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-group4@ttn"
MQTT_API_KEY = "NNSXS.MDRPEA5XLA55WLONUSPD2XUZPTTK6UPYNP3MAJI.5NCB5S7DZ5742W4NAASLDBYA27DY27S4QABMMNAJ5DAF3EDPZZCQ"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

